### ISSUE TITLE
questions about simulate.sh

### ISSUE THREAD

**Issue by huilin-al** [chloroExtractorTeam/benchmark#59]
HI，I want to know why simulate.sh, SEGMENT, REVPOS, PROPORTION are calculated like that.Can you answer it for me, thank you

**Comment by iimog** [comment]
For sure! The relevant portion starts at:
https://github.com/chloroExtractorTeam/benchmark/blob/master/code/simulate.sh#L14 :
```
SEGMENT=$((2 * $READLEN + 100))
REVPOS=$(($SEGMENT - $READLEN + 1))
PROPORTION=$(echo "scale=3; $COV / (2*$READLEN)" | bc -l)
```
- `SEGMENT`: this is the length of the (imaginary) piece of DNA the read pairs are read from both ends. We assume all of them to be long enough to have a 100bp gap between the two reads of each pair. Used by [`seqkit subseq`](https://bioinf.shenwei.me/seqkit/usage/#subseq)
- `REVPOS`: this is the position where the reverse read starts on the segment before we reverse-complement it
- `PROPORTION`: this is the parameter we have to pass to [`seqkit sample`](https://bioinf.shenwei.me/seqkit/usage/#sample). In order to reach the desired per-base coverage `$COV` we need to calculate the sample proportion depending on the read length. The factor 2 comes in as we draw read pairs

Let me know if you have further questions

**Comment by huilin-al** [comment]
Okay, thank you. I already asked my mentor in the morning, and I have become more clear about their meaning by explaining this. But I want to know whether simulate.sh did not add sequencing errors

**Comment by iimog** [comment]
No sequencing error was added

**Comment by huilin-al** [comment]
Does no sequencing error affect the simulated sequencing results?

**Comment by iimog** [comment]
Sequencing errors certainly affect the performance of assembly tools. Our aim of the simulated data was to test the tools under the (unrealistic) assumption of perfect data without any errors. Therefore, we additionally tested all assemblers on realistic data including all the sequencing errors. We did this to see whether some portion of the different performance of assemblers is due to different sensitivity to data quality (uneven coverage, sequencing errors, ...).

**Comment by huilin-al** [comment]
Okay, I already understand why I didn’t add sequencing errors. Thank you very much for your answers. If I have any questions, please ask you again.

**Comment by iimog** [comment]
Sure, feel free to ask again anytime.
